### ISSUE TITLE
Request for more item to increase player's health

### ISSUE THREAD

**Issue by Devlopers** [jorgeavelar98/TakeMeHome#2]
As per user request, tester would like to see the Game to add Heart item to increase Player's Health in the Game
![heart-full-red](https://cloud.githubusercontent.com/assets/7025757/17064784/29a3f210-4ff3-11e6-81b5-716c7ae569e3.png)

**Comment by jorgeavelar98** [comment]
I did, but with a sun in the back to represent energy taken from sunlight in space.
